fos_elastica:
    clients:
        default:
            servers:
                - { host: 127.0.0.1, port: 9200 }
    indexes:
        sylius:
            client: default
            finder: ~
            settings:
                analysis:
                    analyzer:
                        sylius_code_analyzer:
                            type: custom
                            tokenizer: whitespace
                            filter: [lowercase]
                    normalizer:
                        sylius_code_normalizer:
                            type: custom
                            filter: [lowercase]
            types:
                product:
                    mappings:
                        id: { type: integer}
                        code: { type: string, analyzer: sylius_code_analyzer }
                        name: { type: string }
                        raw_name: { type: string, index: not_analyzed, property_path: name }
                        description: { type: string }
                        shortDescription: { type: string }
                        slug: { type: string }
                        raw_createdAt: { type: date, property_path: createdAt }
                        translations:
                            type: "nested"
                            properties:
                                locale: { type: string }
                                name: { type: string }
                                metaKeywords: { type: string }
                                metaDescription: { type: string }
                        variants:
                            type: "nested"
                            properties:
                                code: { type: keyword, index: not_analyzed, normalizer: sylius_code_normalizer }
                                name: { type: string }
                                onHand: { type: integer }
                                onHold: { type: integer }
                                channelPricings:
                                    type: "nested"
                                    properties:
                                        price: { type: integer }
                                        channelCode: { type: string }
                                optionValues:
                                    type: "nested"
                                    properties:
                                        name: { type: string }
                                        value: { type: string }
                                        code: { type: keyword, index: not_analyzed, normalizer: sylius_code_normalizer }
                        attributes:
                            type: "nested"
                            properties:
                                value: { type: keyword, index: not_analyzed, normalizer: sylius_code_normalizer }
                                locale_code: { type: keyword, index: not_analyzed, normalizer: sylius_code_normalizer }
                                attribute:
                                    type: "object"
                                    properties:
                                        code: { type: keyword, index: not_analyzed, normalizer: sylius_code_normalizer }
                        channels:
                            type: "nested"
                            properties:
                                code: { type: string, analyzer: sylius_code_analyzer }
                        productTaxons:
                            type: "nested"
                            properties:
                                taxon:
                                    type: "object"
                                    properties:
                                        code: { type: keyword, index: not_analyzed, normalizer: sylius_code_normalizer }
                                        name: { type: string }
                                position: { type: integer }
                        mainTaxon:
                            type: "object"
                            properties:
                                slug: { type: string }
                                code: { type: keyword, index: not_analyzed, normalizer: sylius_code_normalizer }
                                name: { type: string }
                        images:
                            type: "nested"
                            properties:
                                path: { type: string }
                                type: { type: string }
                        enabled: { type: boolean }
                        isSimple: { type: boolean }
                    persistence:
                        driver: orm
                        model: "%sylius.model.product.class%"
                        provider: ~
                        listener:
                            insert: true
                            update: true
                            delete: true
                        finder: ~
